apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mirror-manage-autoscaler
  namespace: mirror-manage
spec:
  scaleTargetRef:
    name: mirror-manage-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 30 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"