apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: oneid-server-secrets
  namespace: om-webserver
spec:
  name: oneid-server-secrets
  keysMap:
    dburl:
      path: secrets/data/infra-common/om-icsl
      key: dburl
    dbusername:
      path: secrets/data/infra-common/om-icsl
      key: dbusername
    dbpassword:
      path: secrets/data/infra-common/om-icsl
      key: dbpassword
    DEFAULT_AVATAR:
      path: secrets/data/infra-common/om-icsl
      key: DEFAULT_AVATAR