apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: website-autoscaler
  namespace: community-talent-certification-it-system
spec:
  scaleTargetRef:
    name: website
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 30 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"