apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: server-autoscaler
  namespace: openeuler-easyeditor
spec:
  scaleTargetRef:
    name: server
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 30 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"