apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: mindspore-xihe-docs-autoscaler
  namespace: mindspore-website
spec:
  scaleTargetRef:
    name: mindspore-xihe-docs
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 30 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"