---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlookeng-website
  namespace: openlookeng-website
  labels: 
    app: openlookeng-website
spec:
  selector:
    matchLabels:
      app: openlookeng-website 
  template:
    metadata:
      labels:
        app: openlookeng-website
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      nodeSelector:
        autoscaler: "true"
      containers:
      - name: websitepod
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/test_openlookeng_website:3ee278b0aafefedda6acee69286198e0622a56c6
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
