# Resource for ubuntu generic specification slave pods
apiVersion: v1
kind: Service
metadata:
  name: omdata-jenkins-slaves-service
  namespace: jenkins
  labels:
    app: omdata-jenkins-slaves
spec:
  ports:
    - port: 80
      name: port-placeholder
  clusterIP: None
  selector:
    app: omdata-jenkins-slaves

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: omdata-jenkins-slaves
  namespace: jenkins
  labels:
    app: omdata-jenkins-slaves
spec:
  serviceName: omdata-jenkins-slaves-service
  replicas: 1
  selector:
    matchLabels:
      app: omdata-jenkins-slaves
  template:
    metadata:
      labels:
        app: omdata-jenkins-slaves
    spec:
      initContainers:
        - name: slave-init
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins-slave-tools-x86:v0.0.1.20210729
          volumeMounts:
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_USER_NAME
              value: admin
            - name: JENKINS_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osinfra-jenkins-check
                  key: jenkins-slave-token
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local
            - name: JENKINS_SHARE_FOLDER
              value: /home/jenkins/share-config
            - name: EXECUTOR_NUMBERS
              value: "1"
            - name: NODE_LABELS
              value: jenkins
          args: ["$(JENKINS_URL)", "$(JENKINS_USER_NAME)", "$(JENKINS_USER_PASSWORD)", "$(JENKINS_NODE_NAME)", "$(EXECUTOR_NUMBERS)", "$(JENKINS_AGENT_WORKDIR)", "$(NODE_LABELS)", "$(JENKINS_SHARE_FOLDER)"]
      containers:
        - name: jenkins-slave
          image: swr.cn-north-4.myhuaweicloud.com/om/om-data:c8e6a74b1a84f9df2ae1ee1fb5b92f10dfa07b1a
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /home/jenkins/agent-working-dir
              name: omdata-jenkins-slave-workspace-pvc
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          command:
            - /bin/sh
            - -c
            - |
              export JENKINS_SECRET=`cat /home/jenkins/share-config/node_secret.id`;
              exec jenkins-agent
          resources:
            requests:
              cpu: 2000m
              memory: 4000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JENKINS_TUNNEL
              value: jenkins.jenkins.svc.cluster.local:50000
            - name: JENKINS_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local
      volumes:
        - name: jenkins-share-config
          emptyDir: {}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: omdata-jenkins-slave-workspace-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
        storageClassName: "csi-disk-sas"

---
apiVersion: v1
kind: Service
metadata:
  name: docsci-jenkins-slaves-service
  namespace: jenkins
  labels:
    app: docsci-jenkins-slaves
spec:
  ports:
    - port: 80
      name: port-placeholder
  clusterIP: None
  selector:
    app: docsci-jenkins-slaves

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: docsci-jenkins-slaves
  namespace: jenkins
  labels:
    app: docsci-jenkins-slaves
spec:
  serviceName: docsci-jenkins-slaves-service
  replicas: 1
  selector:
    matchLabels:
      app: docsci-jenkins-slaves
  template:
    metadata:
      labels:
        app: docsci-jenkins-slaves
    spec:
      initContainers:
        - name: slave-init
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins-slave-tools-x86:v1.0.20230216113915
          volumeMounts:
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_USER_NAME
              value: admin
            - name: JENKINS_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: osinfra-jenkins-check
                  key: jenkins-slave-token
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local
            - name: JENKINS_SHARE_FOLDER
              value: /home/jenkins/share-config
            - name: EXECUTOR_NUMBERS
              value: "1"
            - name: NODE_LABELS
              value: jenkins
          args: ["$(JENKINS_URL)", "$(JENKINS_USER_NAME)", "$(JENKINS_USER_PASSWORD)", "$(JENKINS_NODE_NAME)", "$(EXECUTOR_NUMBERS)", "$(JENKINS_AGENT_WORKDIR)", "$(NODE_LABELS)", "$(JENKINS_SHARE_FOLDER)"]
      containers:
        - name: docsci-jenkins-slave
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/openeuler-docs-ci:v1
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /home/jenkins/agent-working-dir
              name: docsci-jenkins-slave-workspace-pvc
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          command:
            - /bin/sh
            - -c
            - |
              export JENKINS_SECRET=`cat /home/jenkins/share-config/node_secret.id`;
              exec jenkins-agent
          resources:
            requests:
              cpu: 2000m
              memory: 4000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JENKINS_TUNNEL
              value: jenkins.jenkins.svc.cluster.local:50000
            - name: JENKINS_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local
      volumes:
        - name: jenkins-share-config
          emptyDir: {}
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: docsci-jenkins-slave-workspace-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
        storageClassName: "csi-disk-sas"
