---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitea-repo-deployment
  namespace: gitea-repo
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: gitea-repo
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'gitea-repo'
        vault.hashicorp.com/agent-inject-secret-app.ini: 'internal/data/infra-test/gitea-repo'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-perms-app.ini: "0400"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/agent-inject-template-app.ini: |  
          {{- with secret "internal/data/infra-test/gitea-repo" -}}  
          {{ .Data.data.app }}
          {{- end }}
      labels:
        app: gitea-repo
    spec:
      serviceAccount: gitea-repo
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: gitea-build
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/gitea/gitea-build:6b8591254cd6577c4114dc4140b79453515a6848811a1bfcc52519c6131a4f7a
        imagePullPolicy: IfNotPresent
        args:
        - --config=/vault/secrets/app.ini
        resources:
          requests:
            cpu: "6"
            memory: 10000Mi
          limits:
            cpu: "6"
            memory: 10000Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 3000
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/lib/gitea/
          name: data-volume
        - mountPath: /tmp/
          name: tmp-gitea-data-volume
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: gitea-repo-data-volume
      - name: tmp-gitea-data-volume
        persistentVolumeClaim:
          claimName: tmp-gitea-data-volume
