# StatefulSet for mail core service
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: mailman-core
  namespace: mail
  labels:
    app: mail-suit-service
    component: mail-core-service
spec:
  serviceName: mail-suit-service
  replicas: 1
  selector:
    matchLabels:
      app: mail-suit-service
      component: mail-core-service
  template:
    metadata:
      labels:
        app: mail-suit-service
        component: mail-core-service
    spec:
      containers:
        - name: mailman-core
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/app-mailman/mailman-core-new-build:3d97dff8206e4262c0fa2e218cdacb40e168c56a1672141400
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /opt/mailman/
              name: mailman-core-volume
          env:
            - name: DATABASE_TYPE
              value: mysql
            - name: DATABASE_CLASS
              value: mailman.database.mysql.MySQLDatabase
            - name: MAILMAN_REST_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_core_user
            - name: MAILMAN_REST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailman_core_password
            - name: HYPERKITTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: hyperkitty_api_key
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mysql_user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mysql_password
            - name: HYPERKITTY_URL
            # NOTE: Please update the HYPERKITTY_URL
              value: http://mailman-web-service.mail.svc.cluster.local/hyperkitty
            - name: SMTP_HOST
              value: mailman-exim4-service.mail.svc.cluster.local
            - name: EMAIL_HOST_USER
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: exim4_credential_username
            - name: EMAIL_HOST_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: exim4_credential_password
            - name: MM_HOSTNAME
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailcore_mm_hostname
            - name: MAILMAN_REST_PORT
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailcore_rest_port
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailcore_database_url
            - name: MTA
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailcore_mta
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: mailman-secrets
                  key: mailcore_smtp_port
          # Sed command is used here to force change default charsets to UTF-8
          # related issue: https://gitlab.com/mailman/postorius/issues/325
      #NOTE: Empty dir can't be used in a production dir. Please upgrade it before using.
      volumes:
        - name: mailman-core-volume
          persistentVolumeClaim:
            claimName: config-vol
