---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updating-github-repos
  namespace: infra-cve-manager
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'icms'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/infra-common/infra-cve'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/infra-common/infra-cve" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          serviceAccountName: icms
          containers:
          - name: icms
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-icms:17fca54fcfe6df16d8cfae7e67adffcdea0e2ca2
            env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONFIG_PATH
              value: /vault/secrets/secrets.yaml
            volumeMounts:
            - mountPath: /work/icms/cms/data
              name: cms-data
            command:
              - /bin/sh
              - -c
              - |
                mkdir -p cms/data/json
                mkdir -p cms/data/repo
                python manage.py collect_github_code
          volumes:
          - name: cms-data
            persistentVolumeClaim:
              claimName: cms-share-data-volume

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: updating-other-repos
  namespace: infra-cve-manager
spec:
  schedule: "0 3 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'icms'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/infra-common/infra-cve'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/infra-common/infra-cve" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          serviceAccountName: icms
          containers:
          - name: updating-other-repos
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-icms:17fca54fcfe6df16d8cfae7e67adffcdea0e2ca2
            env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONFIG_PATH
              value: /vault/secrets/secrets.yaml
            volumeMounts:
            - mountPath: /work/icms/cms/data
              name: cms-data
            command:
              - /bin/sh
              - -c
              - |
                mkdir -p cms/data/json
                mkdir -p cms/data/repo
                python manage.py collect_other_code
          volumes:
          - name: cms-data
            persistentVolumeClaim:
              claimName: cms-share-data-volume

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: main-process
  namespace: infra-cve-manager
spec:
  schedule: "0 6 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'icms'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/infra-common/infra-cve'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/infra-common/infra-cve" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          serviceAccountName: icms
          containers:
          - name: main-process
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-icms:17fca54fcfe6df16d8cfae7e67adffcdea0e2ca2
            env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONFIG_PATH
              value: /vault/secrets/secrets.yaml
            volumeMounts:
            - mountPath: /work/icms/cms/data
              name: cms-data
            command:
              - /bin/sh
              - -c
              - |
                python manage.py main_process
          volumes:
          - name: cms-data
            persistentVolumeClaim:
              claimName: cms-share-data-volume

---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: archive-cronjob
  namespace: infra-cve-manager
spec:
  schedule: "0 23 * * *"
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            vault.hashicorp.com/agent-inject: 'true'
            vault.hashicorp.com/role: 'icms'
            vault.hashicorp.com/agent-inject-perms-secrets.yaml: "0700"
            vault.hashicorp.com/agent-run-as-user: "1000"
            vault.hashicorp.com/agent-inject-secret-secrets.yaml: 'internal/data/infra-common/infra-cve'
            vault.hashicorp.com/agent-pre-populate-only: "true"
            vault.hashicorp.com/agent-inject-template-secrets.yaml: |  
              {{- with secret "internal/data/infra-common/infra-cve" -}}  
              {{ .Data.data.config }}
              {{- end }}
        spec:
          restartPolicy: OnFailure
          imagePullSecrets:
          - name: huawei-swr-image-pull-secret
          serviceAccountName: icms
          containers:
          - name: main-process
            image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/app-icms:17fca54fcfe6df16d8cfae7e67adffcdea0e2ca2
            env:
            - name: TZ
              value: Asia/Shanghai
            - name: CONFIG_PATH
              value: /vault/secrets/secrets.yaml
            command:
              - /bin/sh
              - -c
              - |
                ./cms/utils/archive.sh