apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-api
  namespace: chat-api
  labels:
    app: chat-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: chat-api
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'modelapi'
        vault.hashicorp.com/agent-inject-perms-config.ini: "0700"
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-inject-secret-config.ini: 'internal/data/infra-test/modelapi'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/agent-inject-template-config.ini: |  
          {{- with secret "internal/data/infra-test/modelapi" -}}  
          {{ .Data.data.config }}
          {{- end }}
      labels:
        app: chat-api
    spec:
      tolerations:
      - key: "GPU"
        operator: "Equal"
        value: "false"
        effect: "NoSchedule"
      serviceAccountName: modelapi
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: chat-api
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/chatapi/easymodel:master-2f693a
        env:
        - name: LD_LIBRARY_PATH
          value: /usr/local/nvidia/lib64
        - name: APPLICATION_PATH
          value: /vault/secrets/config.ini
        resources:
          limits:
            cpu: 2000m
            memory: 40000Mi
            nvidia.com/gpu: "1"
          requests:
            cpu: 1000m
            memory: 2000Mi
            nvidia.com/gpu: "1"
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 400
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 400
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 8080
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /var/lib/om/model/
          name: chat-api-model-volume
      volumes:
      - name: chat-api-model-volume
        persistentVolumeClaim:
          claimName: obs-chatapi-pvc