---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-playground-backend-tls
  namespace: opengauss-playground-backend-test
spec:
  name: opengauss-playground-backend-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: server.crt
    tls.crt:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: server.crt
    tls.key:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: opengauss-playground-backend-secrets
  namespace: opengauss-playground-backend-test
spec:
  name: opengauss-playground-backend-secrets
  keysMap:
    db-passwd:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: db-passwd
    db-uri:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: db-uri
    db-username:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: db-username
    db-name:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: db-name
    aes-key:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: aes-key
    gitee-client-secret:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: gitee-client-secret
    gitee-client-id:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: gitee-client-id
    oauth2-callback:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: oauth2-callback
    userpool-id:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: userpool-id
    userpool-secret:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: userpool-secret
    container-timeout:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: container-timeout
    course_url:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: course_url
    chapter_url:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: chapter_url
    chapter_detail_url:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: chapter_detail_url
    template_path:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: template_path
    contact_email:
      path: secrets/data/infra-test/opengauss-playground-backend
      key: contact_email



  