apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: om-secrets
spec:
  name: community-tracker-secrets
  keysMap:
    credentials_cfg:
      path: secrets/data/openeuler/kafka
      key: community_tracker_credentials.cfg