---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: anti-poisoning-secrets
  namespace: majun-anti-poisoning
spec:
  name: anti-poisoning-secrets
  keysMap:
    poisonSalt:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: poisonSalt
    spring_data_mongodb_uri:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: spring_data_mongodb_uri
    spring_data_mongodb_dbname:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: spring_data_mongodb_dbname
    spring_data_mongodb_env:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: spring_data_mongodb_env
    primary-ks:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: primary-ks
    standby-ks:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: standby-ks
    work-ks:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: work-ks
    configjson-json:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: configjson-json
    forwarding-call-anti-key:
      path: secrets/data/infra-test/majun-anti-poisoning-icsl
      key: forwarding-call-anti-key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: anti-poisoning-tls
  namespace: majun-anti-poisoning
spec:
  name: anti-poisoning-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-test/domain-tls
      key: tls.cert
    tls.crt:
      path: secrets/data/infra-test/domain-tls
      key: tls.cert
    tls.key:
      path: secrets/data/infra-test/domain-tls
      key: tls.key
