apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: sbom-server-secrets
  namespace: openeuler-sbom
spec:
  name: sbom-server-secrets
  keysMap:
    db_password:
      path: secrets/data/infra-test/sbom-server
      key: db_password
    db_host:
      path: secrets/data/infra-test/sbom-server
      key: db_host
    secret_key:
      path: secrets/data/infra-test/sbom-server
      key: secret_key
    db_name:
      path: secrets/data/infra-test/sbom-server
      key: db_name
    db_uesr:
      path: secrets/data/infra-test/sbom-server
      key: db_uesr
    db_port:
      path: secrets/data/infra-test/sbom-server
      key: db_port

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: sbom-server-tls
  namespace: openeuler-sbom
spec:
  name: sbom-server-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-test/sbom-server
      key: server.crt
    tls.crt:
      path: secrets/data/infra-test/sbom-server
      key: server.crt
    tls.key:
      path: secrets/data/infra-test/sbom-server
      key: server.key
