---
apiVersion: v1
kind: Service
metadata:
  name: mail2list-backend-service
  namespace: mail2list
spec:
  selector:
    app: mail2list-backend
  ports:
  - name: http
    port: 9999
    targetPort: 9999
  type: ClusterIP

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: mail2list-backend
  namespace: mail2list
spec:
  replicas: 0
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: mail2list-backend
  template:
    metadata:
      labels:
        app: mail2list-backend
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - name: mail2list-backend
        image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/mail2list/mail-backend:45c04377883563b483232791c04adb29c42eb8b9
        env:
          - name: OPENGUASS_USER
            valueFrom:
              secretKeyRef:
                key: openeuguass_user
                name: mail2list-backend-secrets
          - name: OPENGUASS_PWD
            valueFrom:
              secretKeyRef:
                key: openeuguass_pwd
                name: mail2list-backend-secrets
          - name: OPENGUASS_URL
            valueFrom:
              secretKeyRef:
                key: openeuguass_url
                name: mail2list-backend-secrets
          - name: OPENGUASS_PORT
            valueFrom:
              secretKeyRef:
                key: openeuguass_port
                name: mail2list-backend-secrets
          - name: OPENGUASS_DATABASE
            valueFrom:
              secretKeyRef:
                key: openeuguass_database
                name: mail2list-backend-secrets
          - name: mine_email
            valueFrom:
              secretKeyRef:
                key: mine_email
                name: mail2list-backend-secrets
          - name: smtp_server
            valueFrom:
              secretKeyRef:
                key: smtp_server
                name: mail2list-backend-secrets
          - name: password
            valueFrom:
              secretKeyRef:
                key: smtp_password
                name: mail2list-backend-secrets
          - name: imap_server
            valueFrom:
              secretKeyRef:
                key: imap_server
                name: mail2list-backend-secrets
          - name: archive_mine_email
            valueFrom:
              secretKeyRef:
                key: archive_mine_email
                name: mail2list-backend-secrets
          - name: archive_smtp_server
            valueFrom:
              secretKeyRef:
                key: archive_smtp_server
                name: mail2list-backend-secrets
          - name: archive_password
            valueFrom:
              secretKeyRef:
                key: archive_password
                name: mail2list-backend-secrets
          - name: archive_name
            valueFrom:
              secretKeyRef:
                key: archive_name
                name: mail2list-backend-secrets
          - name: archive_imap_server
            valueFrom:
              secretKeyRef:
                key: archive_imap_server
                name: mail2list-backend-secrets
          - name: leave_email
            valueFrom:
              secretKeyRef:
                key: leave_email
                name: mail2list-backend-secrets
          - name: leave_smtp_server
            valueFrom:
              secretKeyRef:
                key: leave_smtp_server
                name: mail2list-backend-secrets
          - name: leave_email_password
            valueFrom:
              secretKeyRef:
                key: leave_email_password
                name: mail2list-backend-secrets
          - name: leave_name
            valueFrom:
              secretKeyRef:
                key: leave_name
                name: mail2list-backend-secrets
          - name: leave_imap_server
            valueFrom:
              secretKeyRef:
                key: leave_imap_server
                name: mail2list-backend-secrets
        ports:                                                                                          
        - containerPort: 9999                                                                           
          name: http                                                                                    
          protocol: TCP
        resources:
          limits:
            cpu: 3000m
            memory: 3000Mi
          requests:
            cpu: 3000m
            memory: 3000Mi
        
        