---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cla-data-vol
  namespace: cla
  annotations:
    everest.io/disk-volume-type: SSD
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: csi-disk
