apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: big-model-commit
  namespace: om
  labels:
    app: big-model-commit
spec:
  revisionHistoryLimit: 10
  template:
    metadata:
      labels:
        app: big-model-commit
    spec:
      containers:
        - name: big-model-commit
          image: swr.cn-north-4.myhuaweicloud.com/om/om-collection:0.5.43
          volumeMounts:
            - mountPath: /var/lib/om/config.ini
              subPath: credentials_cfg
              name: mindspore-big-model-commit-secrets-volume
            - mountPath: /mnt
              subPath: bigmodelcommitlog
              name: storage
      volumes:
        - name: mindspore-big-model-commit-secrets-volume
          secret:
            secretName: mindspore-big-model-commit-secrets
        - name: storage
          persistentVolumeClaim:
            claimName: bigmodelcommitlog
