apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: omni-manager-autoscaler
  namespace: omni-manager-backend
spec:
  scaleTargetRef:
    name: omni-manager
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 30 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"