apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana-deployment
  namespace: openeuler-devops
spec:
  selector:
    matchLabels:
      app: kibana
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/agent-pre-populate-only: "true"
        vault.hashicorp.com/role: 'openeuler-devops'
        vault.hashicorp.com/agent-run-as-user: "1000"
        vault.hashicorp.com/agent-run-as-group: "1000"
        vault.hashicorp.com/secret-volume-path: "/etc/ods"
        vault.hashicorp.com/agent-inject-secret-esca: 'internal/data/infra-test/openeuler-devops'
        vault.hashicorp.com/agent-inject-perms-esca: "0400"        
        vault.hashicorp.com/agent-inject-template-esca: |  
          {{- with secret "internal/data/infra-test/openeuler-devops" -}}  
          {{ .Data.data.esCA }}
          {{- end }}
      labels:
        app: kibana
    spec:
      serviceAccount: openeuler-devops
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
      - image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/openeuler-devops/kibana:master-e39f7a
        imagePullPolicy: IfNotPresent 
        name: kibana
        env:
        - name: ELASTICSEARCH_HOSTS
          value: https://192.168.50.125:9200
        - name: ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES
          value: /etc/ods/esca
        resources:
          limits:
            cpu: 500m
            memory: 500Mi
          requests:
            cpu: 500m
            memory: 500Mi
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 20
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5601
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 5601
          timeoutSeconds: 5