apiVersion: v1
kind: ConfigMap
metadata:
  name: github-server-configmap
  namespace: openeuler-software-pkg
data:
  config.yaml: |
    kafka:
      address: "${KAFKA_ADDRESS}"
      version: "${KAFKA_VERSION}"
    message_server:
      group: software-package-github-server
      topics:
        push_code: software_pkg_initialized_test
      message:
        topics_to_notify:
          pushed_code: software_pkg_repo_code_pushed_test
    code:
      robot:
        username: "${GITHUB_ROBOT_USERNAME}"
        token: "${GITHUB_ROBOT_TOKEN}"
      org: orgfsdfsd123
      ci_repo:
        repo: software-package-server
        link: https://gitee.com/weiwei123444/software-package-server
    om_api:
      app_id: "${APP_ID}"
      app_secret: "${APP_SECRET}"
      token_endpoint: https://omapi.osinfra.cn/oneid/manager/token
      user_endpoint: https://omapi.osinfra.cn/oneid/manager/getuserinfo?username=