apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    nginx.ingress.kubernetes.io/custom-http-errors: "400, 500"
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
  name: cloudsca-test
  namespace: sca
spec:
  tls:
    - hosts:
        - test-sca.osinfra.cn
      secretName: sca-test-secret-lts
  rules:
    - host: test-sca.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: sca-gateway
              servicePort: 8080
            path: /gateway/(.*)
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/custom-http-errors: "400, 500"
    nginx.ingress.kubernetes.io/proxy-body-size: 100M
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  name: cloudsca
  namespace: sca
spec:
  tls:
    - hosts:
        - sca.osinfra.cn
      secretName: sca-secret-new-lts
  rules:
    - host: sca.osinfra.cn
      http:
        paths:
          - backend:
              serviceName: sca-web
              servicePort: 8528
            path: /(.*)
          - backend:
              serviceName: sca-gateway
              servicePort: 8080
            path: /gateway/(.*)
