apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: sca-secret
  namespace: sca
spec:
  name: sca-secret
  keysMap:
    client_id:
      path: secrets/data/infra-common/gitee-applications/sca
      key: client_id
    client_secret:
      path: secrets/data/infra-common/gitee-applications/sca
      key: client_secret
    cookie_secret:
      path: secrets/data/infra-common/gitee-applications/sca
      key: cookie_secret
    client_id2:
      path: secrets/data/infra-common/gitee-applications/sca
      key: client_id2
    client_secret2:
      path: secrets/data/infra-common/gitee-applications/sca
      key: client_secret2
    work_ks:
      path: secrets/data/infra-common/gitee-applications/sca
      key: work_ks
    primary_ks:
      path: secrets/data/infra-common/gitee-applications/sca
      key: primary_ks
    standby_ks:
      path: secrets/data/infra-common/gitee-applications/sca
      key: standby_ks
    rootSalt:
      path: secrets/data/infra-common/gitee-applications/sca
      key: rootSalt
    majun_access_token:
      path: secrets/data/infra-common/gitee-applications/sca
      key: majun_access_token

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: sca-secret-new-lts
  namespace: sca
spec:
  name: sca-secret-new-lts
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key