---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: radia-test-tls
  namespace: radia-test
spec:
  name: radia-test-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-test/radia-test
      key: server.crt
    tls.crt:
      path: secrets/data/infra-test/radia-test
      key: server.crt
    tls.key:
      path: secrets/data/infra-test/radia-test
      key: server.key

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: radia-test-secret
  namespace: radia-test
spec:
  name: radia-test-secret
  keysMap:
    rabbitmq_default_user:
      path: secrets/data/infra-test/radia-test
      key: rabbitmq_default_user
    rabbitmq_default_pass:
      path: secrets/data/infra-test/radia-test
      key: rabbitmq_default_pass
    rabbitmq_default_vhost:
      path: secrets/data/infra-test/radia-test
      key: rabbitmq_default_vhost
    cacert.pem:
      path: secrets/data/infra-test/radia-test
      key: cacert_pem
    amqp_user:
      path: secrets/data/infra-test/radia-test
      key: rabbitmq_default_user
    amqp_passwd:
      path: secrets/data/infra-test/radia-test
      key: rabbitmq_default_pass
    amqp_host:
      path: secrets/data/infra-test/radia-test
      key: rabbitmq_default_vhost
    amqp_port:
      path: secrets/data/infra-test/radia-test
      key: rabbitmq_default_port