apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: cvesa-test-autoscaler
  namespace: cvesa-test
spec:
  scaleTargetRef:
    name: cvesa-test-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 30 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"