apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-configmap
  namespace: openeuler-software-pkg
data:
  config.yaml: |
    config_items:
      repos:
        - weiwei123444/community
      ci_label:
        success: ci_successful
        fail: ci_failed
