---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: robot
  namespace: openeuler-software-pkg
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: robot
  template:
    metadata:
      labels:
        app: robot
    spec:
      imagePullSecrets:
        - name: huawei-swr-image-pull-secret
      containers:
        - name: robot
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/openeuler/software-package-server-test:5900d0f534418cb33c65768182b7da7d7a68fea6
          args:
            - --port=8888
            - --config-file=/opt/app/config/config.yaml
            - --msg-config-file=/opt/app/config/msgconfig.yaml
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: software-pkg-secret
                  key: db_host
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: software-pkg-secret
                  key: db_user
            - name: DB_PWD
              valueFrom:
                secretKeyRef:
                  name: software-pkg-secret
                  key: db_pwd
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: software-pkg-secret
                  key: db_name
            - name: KAFKA_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: software-pkg-secret
                  key: kafka_address
          volumeMounts:
            - mountPath: /opt/app/config/config.yaml
              name: robot-configmap
              subPath: config.yaml
            - mountPath: /opt/app/config/msgconfig.yaml
              name: robot-msgconfigmap
              subPath: msgconfig.yaml
      volumes:
        - configMap:
            defaultMode: 420
            name: robot-configmap
          name: robot-configmap
        - configMap:
            defaultMode: 420
            name: robot-msgconfigmap
          name: robot-msgconfigmap


