apiVersion: v1
kind: Service
metadata:
  name: robot-service
  namespace: openeuler-software-pkg
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8888
  selector:
    app: robot
  type: ClusterIP
