apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: jenkins-backup
  namespace: jenkins
spec:
  schedule: "10 1 * * *"
  startingDeadlineSeconds: 180
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: bak-jenkins
            image: swr.cn-north-4.myhuaweicloud.com/openeuler/bak-jenkins:v1.4.0
            imagePullPolicy: IfNotPresent
            env:
            - name: secret
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: secret
            - name: git_token
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: git_token
            - name: huaweiclound_obs_url
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: huaweiclound_obs_url
            - name: huaweiclound_obs_ak
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: huaweiclound_obs_ak
            - name: huaweiclound_obs_sk
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: huaweiclound_obs_sk
            - name: url
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: url
            - name: username
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: username
            - name: password
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: password
            - name: bak_domain
              valueFrom:
                secretKeyRef:
                  name: jenkins-backup-secret
                  key: bak_domain
            ports:
            - containerPort: 80
              name: http
              protocol: TCP
          restartPolicy: OnFailure