---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: osinfra-jenkins
spec:
  name: osinfra-jenkins
  keysMap:
    jenkins-admin-user:
      path: secrets/data/infra-common/jenkins
      key: jenkins-admin-user
    jenkins-admin-password:
      path: secrets/data/infra-common/jenkins
      key: jenkins-admin-password
    jenkins-admin-token:
      path: secrets/data/infra-common/jenkins
      key: jenkins-admin-token
    client_id:
      path: secrets/data/infra-common/github-applications/infra-jenkins
      key: client_id
    client_secret:
      path: secrets/data/infra-common/github-applications/infra-jenkins
      key: client_secret
    cookie_secret:
      path: secrets/data/infra-common/github-applications/infra-jenkins
      key: cookie_secret

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: jenkins-backup-secret
  namespace: jenkins
spec:
  name: jenkins-backup-secret
  keysMap:
    secret:
      path: secrets/data/infra-common/jenkins
      key: secret
    git_token:
      path: secrets/data/infra-common/jenkins
      key: git_token
    huaweiclound_obs_url:
      path: secrets/data/infra-common/jenkins
      key: huaweiclound_obs_url
    huaweiclound_obs_ak:
      path: secrets/data/infra-common/jenkins
      key: huaweiclound_obs_ak
    huaweiclound_obs_sk:
      path: secrets/data/infra-common/jenkins
      key: huaweiclound_obs_sk
    url:
      path: secrets/data/infra-common/jenkins
      key: url
    username:
      path: secrets/data/infra-common/jenkins
      key: username
    password:
      path: secrets/data/infra-common/jenkins
      key: password
    bak_domain:
      path: secrets/data/infra-common/jenkins
      key: bak_domain

---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: jenkins-tls
  namespace: jenkins
spec:
  name: jenkins-tls
  keysMap:
    ca.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.crt:
      path: secrets/data/infra-common/osinfra-cn
      key: server.crt
    tls.key:
      path: secrets/data/infra-common/osinfra-cn
      key: server.key