apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: website-deployment-autoscaler
  namespace: mindspore-website2
spec:
  scaleTargetRef:
    name: website-deployment
  triggers:
  - type: cron
    metadata:
      timezone: Asia/Shanghai
      start: 30 8 * * *
      end: 55 23 * * *
      desiredReplicas: "1"