apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-configmap
  namespace: openeuler-software-pkg
data:
  config.yaml: |
    code:
      pkg_src_org: euler-ttttt
      robot:
        username: "${ROBOT_USERNAME}"
        token: "${ROBOT_TOKEN}"
      ci_repo:
        repo: test
        link: https://gitee.com/weiwei123444/test.git
    kafka:
      address: "${KAFKA_ADDRESS}"
    email:
      maintainer_email: ${MAINTAINER_EMAIL}
      email:
        auth_code: "${EMAIL_AUTH_CODE}"
        from: "${EMAIL_FROM}"
        host: "${EMAIL_HOST}"
        port: ${EMAIL_PORT}
    watch:
      pkg_org: euler-ttttt
      robot_token: "${ROBOT_TOKEN}"
    community:
      pkg_org: euler-ttttt
      robot_token: "${ROBOT_TOKEN}"
      community_org: weiwei123444
      community_repo: community
      ci_success_label: ci_successful
      ci_failure_label: ci_failed
    postgresql:
      db:
        host: "${DB_HOST}"
        port: 5432
        user: "${DB_USER}"
        pwd: "${DB_PWD}"
        name: "${DB_NAME}"
        life: 2
        max_conn: 500
        max_idle: 250
      table:
        software_pkg_pr: software_pkg_watch_gitee
    encryption:
      encryption_key: "${ENCRYPTION_KEY}"
    pull_request:
      robot:
        username: "${ROBOT_USERNAME}"
        token: "${ROBOT_TOKEN}"
        email: "${ROBOT_EMAIL}"
        repo: community
        link: https://gitee.com/weiwei123444/community.git
      community_robot:
        token: "${ROBOT_MERGE_PR_TOKEN}"
        org: euler-ttttt
        repo: community
        link: https://gitee.com/euler-ttttt/community.git
      software_pkg:
        endpoint: https://software-pkg.test.osinfra.cn/zh/package-detail/
    message_server:
      user_agent: software-pkg
      group_name: software-package
      topics:
        new_pkg: software_pkg_approved_test
        community_event: openeuler-community_test
      message:
        topics_to_notify:
          ci_passed: software_pkg_initialized_test
          created_repo: software_pkg_repo_created_test
          pushed_code: software_pkg_code_saved_test