apiVersion: v1
kind: ConfigMap
metadata:
  name: robot-configmap
  namespace: openeuler-software-pkg
data:
  config.yaml: |
    code:
      pkg_src_org: euler-ttttt
      robot:
        username: "${ROBOT_USERNAME}"
        token: "${ROBOT_TOKEN}"
      ci_repo:
        repo: software-package-server
        link: https://gitee.com/weiwei123444/software-package-server
    kafka:
      address: "${KAFKA_ADDRESS}"
      version: "${KAFKA_VERSION}"
    message_server:
      user_agent: software-pkg
      group_name: software-package
      topics:
        push_code: software_pkg_initialized_test
      message:
        topics_to_notify:
          pushed_code: software_pkg_repo_code_pushed_test
    om_api:
      app_id: "${APP_ID}"
      app_secret: "${APP_SECRET}"
      token_endpoint: https://omapi.osinfra.cn/oneid/manager/token
      user_endpoint: https://omapi.osinfra.cn/oneid/manager/getuserinfo?username=